### ISSUE TITLE
FATAL ERROR : Failed to load function std@bytes_compare16

### ISSUE THREAD

**Issue by Ilir-Liburn** [HaxeFoundation/hashlink#259]
src\module.c(311) : FATAL ERROR : Failed to load function std@bytes_compare16

after rc.3 was installed

**Comment by kapep** [comment]
I get the same error when trying to run a simple 'hello world' application.

OS: Windows 10
Haxe version (64 bit): 4.0.0-rc.3+e3df7a448 
HashLink version: HL/JIT 1.9.0

**Comment by Gama11** [comment]
You need HL 1.10.0 (not released yet).

I think alternatively, you can also compile with `-D hl_ver=1.9.0`.

**Comment by kapep** [comment]
> I think alternatively, you can also compile with `-D hl_ver=1.9.0`.

Thanks, that worked!

**Comment by thatpanda** [comment]
> 
> 
> I get the same error with rc.3 when trying to run a simple 'hello world' application. Compiling and running it with rc.2 works fine.
> 
> OS: Windows 10
> Haxe version (64 bit): 4.0.0-rc.3+e3df7a448
> HashLink version: HL/JIT 1.9.0

Thanks! I just started learning Haxe and ran into the same issue with the hello world example. Downgrading to Haxe 4.0.0-rc.2 worked for me.

**Comment by uvtc** [comment]
I just upgraded to Haxe 4 rc3 (on Debian Testing, using the Linux 64-bit binary release) and hit this same error.

    src/module.c(311) : FATAL ERROR : Failed to load function std@bytes_compare16

Searched and found this issue. Downgraded, installing Haxe 4 rc2 (again, the binary release), and works now.

**Comment by ncannasse** [comment]
4.0 RC3 by default uses HL 1.10 , you can compile with RC3 for HL 1.9 by adding `-D hl_ver=1.9.0`
I'll release HL 1.10 now.

**Comment by jefvel** [comment]
I get a similar error message; 
```
src/module.c(459) : FATAL ERROR : Failed to load function std@bytes_compare16
```
when compiling a hello world project with haxe `4.0.0-rc.5+4a745347f` and running hl `HL/JIT 1.10.0` from git.

**Comment by ncannasse** [comment]
@jefvel make sure that hl 1.10 libhl.so is correctly installed on your system, so it does not use an older libhl

**Comment by jefvel** [comment]
@ncannasse ah, my bad! I forgot I had copied it from `/usr/local/lib` to `/usr/lib`, since Arch linux doesn't look in `/usr/local/lib` by default. It works after updating it. Thanks
