### ISSUE TITLE
Browse file not working as expected in Linux

### ISSUE THREAD

**Issue by amir-rezai** [HaxeFoundation/hashlink#371]
I expected `hl.UI.loadFile` function to open a file browse window but it's not.
this issue occurred while I was using heaps and when I tracked the code I realized this issue resided in Hashlink.

Hashlink is not opening the default file browse window in linux.

I'm using i3, archlinux.
Nothing happens when I use the function even in debug mode.

**Comment by YRTV** [comment]
UI library not implemented for Linux yet. It's just temporary stub https://github.com/HaxeFoundation/hashlink/blob/master/libs/ui/ui_stub.c

**Comment by manjav** [comment]
Also not working on Windows
https://github.com/haxelime/lime/issues/1404

**Comment by YRTV** [comment]
Tested it. This code works on Windows release `HL/JIT 1.11.0 (c)2015-2019 Haxe Foundation`. `FileOptions` structure can't be empty, but compiler should warn about missing arguments.

```
class Main {
    static function main() {
        var opts:FileOptions = {title: "myfileselector"};
        hl.UI.loadFile(opts);
    }
}

```

**Comment by maxwtBvGBfwR** [comment]
Well I tested same code Linux release `HL/JIT 1.12.0 (c)2015-2020 Haxe Foundation`. 
But it's not working yet and it complains about:
```
undefined reference to `ui_ui_init'
undefined reference to `ui_ui_choose_file'
```

And that's weird because ui_ui_init is defined in ui.hdll and it's already installed in linker path, same as sdl and other libraries which are working but as you stated the `ui_init` function is not implemented for linux and it uses and loads windows .dll libraries.

The point is linux distributions use different ui loaders, some use [GtkFileChooser](https://developer.gnome.org/gtk3/stable/GtkFileChooser.html) and some use [QtUiLoader](https://doc.qt.io/archives/qt-4.8/quiloader.html) as long as OpenGL and SDL which are already ported does not have ui loader, it's a hell lot of work to write `gtk.hdll` or `qt.hdll` for hashlink, so it's some kind of request for a minimal ui loader for hashlink.

**Comment by manjav** [comment]
دیدم دمت گرم امیر جان

**Comment by YRTV** [comment]
`/usr/local/lib` where `make install` puts hdlls  is not searched by dynamic loader on arch by default. `export LD_LIBRARY_PATH=/usr/local/lib` will fix it for hl bytecode during one shell session. 

Read manpage if you want more options to do it.

```
pacman --needed -S man-pages man-db
man ld.so
```
If you need HL/C compilation just link statically against all needed hdlls.

Qt5 is c++ framework so it's out of competition.

Turn UI.hdll function into GtkFileChooser wrapper if you need fast solution. Make sure you have file manager which can be called and it's set as default.  i3wm if I remember correctly does not have file choose dialog. It's just window manager on top of pure X.org.
