### ISSUE TITLE
Profiler doesn't compile on Ubuntu 18.04

### ISSUE THREAD

**Issue by tobil4sk** [HaxeFoundation/hashlink#506]
This is an oversight from #490

Here's the error log:

```
/home/runner/hashlink/src/profile.c: In function ‘pause_thread’:
/home/runner/hashlink/src/profile.c:148:3: warning: implicit declaration of function ‘tgkill’; did you mean ‘kill’? [-Wimplicit-function-declaration]
   tgkill(getpid(), t->tid, SIGPROF);
   ^~~~~~
   kill
[43/50] Building C object CMakeFiles/hl.dir/src/jit.c.o
[44/50] Building C object libs/fmt/CMakeFiles/fmt.hdll.dir/sha1.c.o
[45/50] Linking C executable bin/hl
FAILED: bin/hl 
: && /usr/bin/cc  -rdynamic CMakeFiles/hl.dir/src/code.c.o CMakeFiles/hl.dir/src/jit.c.o CMakeFiles/hl.dir/src/main.c.o CMakeFiles/hl.dir/src/module.c.o CMakeFiles/hl.dir/src/debugger.c.o CMakeFiles/hl.dir/src/profile.c.o -o bin/hl  -Wl,-rpath,/home/runner/hashlink_build/bin:  bin/libhl.so.1.12.0  -lm  -ldl  -lpthread && :
CMakeFiles/hl.dir/src/profile.c.o: In function `pause_thread':
profile.c:(.text+0xcc): undefined reference to `tgkill'
collect2: error: ld returned 1 exit status
```

This is because ubuntu 18.04 ships with an older version of glibc than the one shipped with ubuntu 20.04 (where it works fine).

From nicolas:
> https://man7.org/linux/man-pages/man2/tkill.2.html , we need something like if glibc < 2.20 #define tgkill(_,tid,sig) syscall(SYS_tkill,tid,sig)
